### ISSUE TITLE
s1l3nt - castVoteBySig allows votes on proposals that are not Active

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-olympus-on-chain-governance-judging#25]
s1l3nt

high

# castVoteBySig allows votes on proposals that are not Active

## Summary
`castVoteBySig` function does not check if the state of the proposal is Active, a voter can vote on proposals that are already `Vetoed`, `Canceled`, `Defeated` and `Executed`. This vulnerability leads to bad voting calculation of a proposal.

Example:
- proposal 1 executed with 2 votes in favor and 2 votes against
- proposal voting period ends
- Voter B who was away, votes on the proposal in favor
- Bad voting calculation, now the proposal is 3 votes in favor and 2 against.

## Vulnerability Detail
```solidity
function castVoteBySig(
        uint256 proposalId,
        uint8 support,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external {
        //
       // Missing to verify the state of the proposal, if it is active for voting. Check the recommendation fix below
       // 
        bytes32 domainSeparator = keccak256(
            abi.encode(DOMAIN_TYPEHASH, keccak256(bytes(name)), getChainIdInternal(), address(this))
        );
        bytes32 structHash = keccak256(abi.encode(BALLOT_TYPEHASH, proposalId, support));
        bytes32 digest = keccak256(abi.encodePacked("\x19\x01", domainSeparator, structHash));
        address signatory = ecrecover(digest, v, r, s);
        if (signatory == address(0)) revert GovernorBravo_InvalidSignature();
        emit VoteCast(
            signatory,
            proposalId,
            support,
            castVoteInternal(signatory, proposalId, support),
            ""
        );
    }
```
## Impact
Vote on proposals that are not Active, this includes voting on proposals that are Vetoed, Canceled, Defeated and were successfully Executed. This may lead to `Bad voting` calculation at the end.

## Code Snippet
https://github.com/sherlock-audit/2024-01-olympus-on-chain-governance/blob/main/bophades/src/external/governance/GovernorBravoDelegate.sol#L403

## Tool used

Manual Review

## Recommendation
The `castVoteBySig` is missing this line in the beginning of its body: 
```solidity
if (state(proposalId) != ProposalState.Active) revert GovernorBravo_Vote_Closed();
```

```solidity
function castVoteBySig(
        uint256 proposalId,
        uint8 support,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external {
       if (state(proposalId) != ProposalState.Active) revert GovernorBravo_Vote_Closed();
      
      bytes32 domainSeparator = keccak256(
            abi.encode(DOMAIN_TYPEHASH, keccak256(bytes(name)), getChainIdInternal(), address(this))
        );
       // ....
```

**Comment by 0xLienid** [comment]
not true. this is caught by `castVoteInternal` which is called in the event
